package system_product_app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author Rafael De La Cruz
 */

//Herencia: Hereda Los Elementos de la Superclase javax.swing.JFrame.

public class SectionLogin extends javax.swing.JFrame {
    
 Database db = Database.getInstance();
        
        Connection connect = db.Conexion();
        
         SectionErr SE = SectionErr.getInstance();
        
    /**
     * Creates new form SectionLogin
     * 
     * 
     */
    public SectionLogin() {
        initComponents();
        
         setResizable(false);
         
         setVisible(true);
       
       setLocationRelativeTo(null);
       
       setIconImage(new ImageIcon(getClass().getResource("/Icons/Logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserLogin = new javax.swing.JTextField();
        RegistreLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PassLogin = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        OpenLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        UserLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UserLogin.setBorder(null);

        RegistreLogin.setBackground(new java.awt.Color(0, 153, 153));
        RegistreLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RegistreLogin.setForeground(new java.awt.Color(255, 255, 255));
        RegistreLogin.setText("Registrarse");
        RegistreLogin.setBorder(null);
        RegistreLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistreLogin.setFocusPainted(false);
        RegistreLogin.setFocusable(false);
        RegistreLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistreLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserLogin.png"))); // NOI18N
        jLabel2.setText("Usuario");

        PassLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PassLogin.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PassLogin.png"))); // NOI18N
        jLabel8.setText("Contraseña");

        OpenLogin.setBackground(new java.awt.Color(0, 204, 204));
        OpenLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        OpenLogin.setForeground(new java.awt.Color(255, 255, 255));
        OpenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Open.png"))); // NOI18N
        OpenLogin.setText("Entrar");
        OpenLogin.setActionCommand("");
        OpenLogin.setBorder(null);
        OpenLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenLogin.setFocusPainted(false);
        OpenLogin.setFocusable(false);
        OpenLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                .addComponent(PassLogin)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(OpenLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(RegistreLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(PassLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpenLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistreLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenLoginActionPerformed
     
          
         if(UserLogin.getText().equals("")|| PassLogin.getText().equals("")){
        
        SE.GetMessagerErr("Complete Todos Los Campos");
        
        SE.setVisible(true);
        
        return;
        
        }
        
        
        try {
			 //        Polimorfismo: Usa una misma función para asignar diversos valores a diversos elementos.
			
			
                        PreparedStatement  UserAcess = connect.prepareStatement("Select * From usuarios where UserName = '"+UserLogin.getText()+"'");
						
			PreparedStatement  PassAcess = connect.prepareStatement("Select * From usuarios where Password = '"+PassLogin.getText()+"'");
						
			
			ResultSet DataUser = UserAcess.executeQuery(); 
                        
                        ResultSet DataPass = PassAcess.executeQuery(); 
                        
                         String [] DatosUser = new String[1];
				 
                        String [] DatosPass = new String[1];
                        
                        while(DataUser.next()) {
							
							
							DatosUser[0] = DataUser.getString(2);
							
						}
						
						
						while(DataPass.next()) {
							
							
							DatosPass[0] = DataPass.getString(7);
							
						}
                                          
                                 if(UserLogin.getText().equals(DatosUser[0]) && PassLogin.getText().equals(DatosPass[0])) {
                                 
                                     SectionOptions SO = new SectionOptions();
        
                                    SO.setVisible(true);
        
                                    this.setVisible(false);
                                 }
                                 
                                 else{
                                 
                                 SE.GetMessagerErr("Usuario y/o Contraseña Incorrectos");
        
                                SE.setVisible(true);
        
                                return;
                                 
                                 }
                                                            
                        
          }catch(SQLException ex){}
        
        
        
        
    }//GEN-LAST:event_OpenLoginActionPerformed

    private void RegistreLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistreLoginActionPerformed
       
        SectionRegistre SR = new SectionRegistre();
        
        SR.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_RegistreLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SectionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SectionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SectionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SectionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SectionLogin().setVisible(true);
            }
        });
    }
    
    //    Encapsulamiento: Restringe el uso de estos elementos a solo esta clase.
    
        //    Abstracción: Define y declara los elementos que compondran esta clase.

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenLogin;
    private javax.swing.JPasswordField PassLogin;
    private javax.swing.JButton RegistreLogin;
    private javax.swing.JTextField UserLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

