package system_product_app;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.ImageIcon;

/**
 *
 * @author Rafael De La Cruz
 */

//Herencia: Hereda Los Elementos de la Superclase javax.swing.JFrame

public class SectionRegistre extends javax.swing.JFrame {

        Database db = Database.getInstance();
        
        Connection connect = db.Conexion();
         
          SectionErr SE = SectionErr.getInstance();
         
    public SectionRegistre() {
        initComponents();
        
        setResizable(false);
       
       setLocationRelativeTo(null);
       
       setIconImage(new ImageIcon(getClass().getResource("/Icons/Logo.png")).getImage());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserRegistre = new javax.swing.JTextField();
        NameRegistre = new javax.swing.JTextField();
        LastNameRegistre = new javax.swing.JTextField();
        PhoneRegistre = new javax.swing.JTextField();
        EmailRegistre = new javax.swing.JTextField();
        OpenRegistre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PassRegistre = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        CPassRegistre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Registre.png"))); // NOI18N
        jLabel1.setText("Registro");

        UserRegistre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UserRegistre.setBorder(null);

        NameRegistre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NameRegistre.setBorder(null);

        LastNameRegistre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LastNameRegistre.setBorder(null);

        PhoneRegistre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneRegistre.setBorder(null);

        EmailRegistre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailRegistre.setBorder(null);

        OpenRegistre.setBackground(new java.awt.Color(0, 204, 204));
        OpenRegistre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        OpenRegistre.setForeground(new java.awt.Color(255, 255, 255));
        OpenRegistre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Open.png"))); // NOI18N
        OpenRegistre.setText("Registrarse");
        OpenRegistre.setBorder(null);
        OpenRegistre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenRegistre.setFocusPainted(false);
        OpenRegistre.setFocusable(false);
        OpenRegistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenRegistreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmar Contraseña");

        PassRegistre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PassRegistre.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");

        CPassRegistre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CPassRegistre.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmailRegistre, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                .addComponent(UserRegistre)
                                .addComponent(PhoneRegistre)
                                .addComponent(LastNameRegistre)
                                .addComponent(NameRegistre)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(PassRegistre)
                                .addComponent(CPassRegistre)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(OpenRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LastNameRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhoneRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPassRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OpenRegistre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenRegistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenRegistreActionPerformed
        
         //        Polimorfismo: Usa una misma función para asignar diversos valores a diversas variables.
        
         String User = UserRegistre.getText();
				
	 String Name = NameRegistre.getText();
				
	 String LName = LastNameRegistre.getText();
				
	String Phone = PhoneRegistre.getText();
				
	String Email = EmailRegistre.getText();
        
        String Pass = PassRegistre.getText();
				
	String CPass = CPassRegistre.getText();
       
       
       
        if(User.equals("")|| Name.equals("")||LName.equals("")||Phone.equals("")||Email.equals("")||Pass.equals("")||CPass.equals("")){
        
        SE.GetMessagerErr("Complete Todos Los Campos");
        
        SE.setVisible(true);
        
        return;
        
        }
        
         if(CPass.equals(Pass)){}
         
         else{
         
         SE.GetMessagerErr("Las Contraseñas No Coinciden");
         
         PassRegistre.setText("");
         
         CPassRegistre.setText("");
        
        SE.setVisible(true);
        
        return;
         
         }
        
        
        try{
        
           
        
        PreparedStatement  isrt = connect.prepareStatement("INSERT INTO usuarios (UserName,Nombre,Apellido,Telefono,Email,Password) VALUES (?,?,?,?,?,?)");
	
                                 //        Polimorfismo: Usa una misma función para asignar diversos valores a un mismo elemento.
                                
				isrt.setString(1, User);
				
				isrt.setString(2, Name);
				
				isrt.setString(3, LName);
				
				isrt.setString(4, Phone);
				
				isrt.setString(5, Email);
				
				isrt.setString(6, CPass);
                                
         isrt.executeUpdate();
        
        
        }catch(SQLException ex){}
        
       
        this.setVisible(false);
        
        SectionLogin SL = new SectionLogin();
       
    
    }//GEN-LAST:event_OpenRegistreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SectionRegistre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SectionRegistre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SectionRegistre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SectionRegistre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SectionRegistre().setVisible(true);
            }
        });
    }
    
    //    Encapsulamiento: Restringe el uso de estos elementos a solo esta clase.
    
        //    Abstracción: Define y declara los elementos que compondran esta clase.

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CPassRegistre;
    private javax.swing.JTextField EmailRegistre;
    private javax.swing.JTextField LastNameRegistre;
    private javax.swing.JTextField NameRegistre;
    private javax.swing.JButton OpenRegistre;
    private javax.swing.JPasswordField PassRegistre;
    private javax.swing.JTextField PhoneRegistre;
    private javax.swing.JTextField UserRegistre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
